//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatoWeb.Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.factura_producto_compra = new HashSet<factura_producto_compra>();
            this.factura_producto_venta = new HashSet<factura_producto_venta>();
        }
    
        public int id { get; set; }
        public string codigo_original { get; set; }
        public string codigo_alterno { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public string descripcion { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> marca_id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string urlImagen { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_producto_compra> factura_producto_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_producto_venta> factura_producto_venta { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
